version: '3'

services:
  flask-chatbot.pri:
    build:
      context: .
      dockerfile: dockerfile
    ports:
        - "5000:5000"
    environment:
      line_channel_access_token: 'Your line chatbot access token'
      line_channel_secret: 'Your line channel secret'
    volumes:
        - .:/app